name: "fetch-upstream"
description: "Fetch an artifact from the merge-base commit and re-upload it"
inputs:
  artifact-name:
    description: "Original artifact name"
    required: true
  token:
    description: "Token with actions:read; can be GITHUB_TOKEN"
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Checkout user repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Compute commit id of the merge base
      id: merge_base
      shell: bash
      run: |
        base_ref="${{ github.event.pull_request.base.ref }}"
        git fetch origin "$base_ref" --depth=1 --no-tags
        sha=$(git merge-base "$GITHUB_SHA" "origin/$base_ref")
        echo "sha=$sha" >> "$GITHUB_OUTPUT"

    - name: Determine upstream repository
      id: upstream_repo
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.head.repo.fork }}" == "true" ]]; then
          echo "owner=${{ github.event.pull_request.base.repo.owner.login }}" >> "$GITHUB_OUTPUT"
          echo "repo=${{ github.event.pull_request.base.repo.name }}" >> "$GITHUB_OUTPUT"
        else
          echo "owner=${{ github.repository_owner }}" >> "$GITHUB_OUTPUT"
          echo "repo=${{ github.event.repository.name }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Download artifact from upstream
      uses: dawidd6/action-download-artifact@v11
      with:
        name: ${{ inputs.artifact-name }}
        path: upstream
        commit: ${{ steps.merge_base.outputs.sha }}
        repo: ${{ steps.upstream_repo.outputs.owner }}/${{ steps.upstream_repo.outputs.repo }}
        github_token: ${{ inputs.token }}

    - name: Upload upstream artifact
      uses: actions/upload-artifact@v4
      with:
        name: upstream-${{ inputs.artifact-name }}
        path: upstream
